<?php

/**
 * @file
 * Functions to support Jen's theme.
 */

/**
 * Prepares variables for page templates.
 *
 * @see hook_preprocess_HOOK()
 */
function jen_preprocess_page(&$variables) {

  // How to add a new variable for use in a twig template.
  $variables['path'] = drupal_get_path('theme', 'jen') . '/images/';

  // Don't do this...  we can to this in the Twig template instead!
    // $variables['date'] = date('Y');
}

